# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
array1=np.array([1,43,54,24,87,34,65,98])
# Create a 2-dimensional NumPy array using np.array()
array2=np.array([[1,2,3],[4,5,6]])
# Create a 3-dimensional Numpy array using np.array()
array3=np.array([[[1,2,3],
                 [4,5,6]],
                [[7,8,9],
                 [1,2,3]]])
array1
array2
array3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [1, 2, 3]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
array1.size,array1.shape,type(array1)

(8, (8,), numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
array2.size,array2.shape,type(array2)

(6, (2, 3), numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
array3.size,array3.shape,type(array3)

(12, (2, 2, 3), numpy.ndarray)

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
array1_df=pd.DataFrame(array1)
array1_df

0
0   1
1  43
2  54
3  24
4  87
5  34
6  65
7  98

In [7]:
# Create an array of shape (10, 2) with only ones
ones_array=np.ones((10,2))
ones_array

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
# Create an array of shape (7, 2, 3) of only zeros
zeros_array=np.zeros((7,2,3))
zeros_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
# Create an array within a range of 0 and 100 with step 3
random_array1=np.random.randint(100,size=(3,3))
random_array1

array([[47, 55, 62],
       [76,  2, 73],
       [62, 83, 76]])

In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array2=np.random.randint(10,size=(7,2))
random_array2

array([[2, 6],
       [3, 2],
       [1, 1],
       [9, 9],
       [4, 4],
       [9, 0],
       [3, 4]])

In [11]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array3=np.random.random(size=(3,5))
random_array3

array([[0.553884  , 0.202867  , 0.61922329, 0.20269271, 0.47343036],
       [0.50568019, 0.65604176, 0.78189484, 0.81131166, 0.65725019],
       [0.52478975, 0.70651538, 0.06395675, 0.22160133, 0.29111625]])

In [12]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array4=np.random.randint(10,size=(4,6))
random_array4

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

#### same becaues of seed function

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [13]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable

random_array5=np.random.randint(1,10,size=(3,7))
# Find the unique numbers in the array you just created
np.unique(random_array5)


array([1, 2, 3, 4, 5, 7, 9])

In [14]:
# Find the 0'th index of the latest array you created
import pandas as pd
random_array4[0]

array([6, 3, 7, 4, 6, 9])

In [15]:
# Get the first 2 rows of latest array you created
random_array4[:2]

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7]])

In [16]:
# Get the first 2 values of the first 2 rows of the latest array
random_array4[2:,:2]

array([[7, 2],
       [5, 1]])

In [17]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array5=np.random.randint(10,size=(3,5))
ones_array=np.ones((3,5))

In [18]:
# Add the two arrays together
latest_array=random_array5+ones_array

In [19]:
# Create another array of ones of shape (5, 3)
ones_array2=np.ones((5,3))

In [20]:
# Try add the array of ones and the other most recent array together
ones_array+ones_array2

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

##### Ans--> shape is not same

In [21]:
# Create another array of ones of shape (3, 5)
ones_array3=np.ones((3,5))

In [22]:
# Subtract the new array of ones from the other most recent array
ones_array-ones_array3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
# Multiply the ones array with the latest array
latest_array*ones_array3

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [24]:
# Take the latest array to the power of 2 using '**'
latest_array**2

array([[ 49.,  64.,   9.,   1.,  16.],
       [  4.,  64.,  16.,   4.,  36.],
       [ 36., 100.,  16.,  36.,   4.]])

In [25]:
# Do the same thing with np.square()
np.square(latest_array)

array([[ 49.,  64.,   9.,   1.,  16.],
       [  4.,  64.,  16.,   4.,  36.],
       [ 36., 100.,  16.,  36.,   4.]])

In [26]:
# Find the mean of the latest array using np.mean()
np.mean(latest_array)

4.866666666666666

In [27]:
# Find the maximum of the latest array using np.max()
np.max(latest_array)

10.0

In [28]:
# Find the minimum of the latest array using np.min()
np.min(latest_array)

1.0

In [29]:
# Find the standard deviation of the latest array
np.std(latest_array)

2.578543947441829

In [30]:
# Find the variance of the latest array
np.var(latest_array)

6.648888888888889

In [31]:
# Reshape the latest array to (3, 5, 1)
latest_array.reshape(3,5,1)

array([[[ 7.],
        [ 8.],
        [ 3.],
        [ 1.],
        [ 4.]],

       [[ 2.],
        [ 8.],
        [ 4.],
        [ 2.],
        [ 6.]],

       [[ 6.],
        [10.],
        [ 4.],
        [ 6.],
        [ 2.]]])

In [32]:
# Transpose the latest array
latest_array.T

array([[ 7.,  2.,  6.],
       [ 8.,  8., 10.],
       [ 3.,  4.,  4.],
       [ 1.,  2.,  6.],
       [ 4.,  6.,  2.]])

What does the transpose do?

###### Ans--> swap([i][j],[j][i])

In [33]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
rdm1=np.random.randint(10,size=(3,2))
rdm2=np.random.randint(10, size=(3,3))

In [34]:
# Perform a dot product on the two newest arrays you created
np.dot(rdm2,rdm1)

array([[163,  53],
       [ 94,  55],
       [209,  81]])

In [35]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
random1=np.random.randint(10,size=(4,3))
random2=np.random.randint(10,size=(4,3))

In [36]:
# Perform a dot product on the two newest arrays you created
np.dot(random1,random2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

##### we can fix it by taking transpose of a matrix

In [37]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(random1,random2.T)


array([[ 24, 102,  96,   8],
       [ 16, 114, 106,  63],
       [ 22, 123, 114,  56],
       [  8,  60,  58,   7]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [38]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
a=np.random.randint(10,size=(4,7))
b=np.random.randint(10,size=(4,7))

In [39]:
# Compare the two arrays with '>'
a>b

array([[ True, False,  True, False,  True, False, False],
       [False, False, False, False, False, False, False],
       [ True,  True, False, False,  True,  True, False],
       [False, False, False, False, False,  True,  True]])

What happens when you compare the arrays with `>`?

##### giving bool matrix

In [40]:
# Compare the two arrays with '>='
a>=b

array([[ True,  True,  True, False,  True, False, False],
       [False, False, False, False, False, False, False],
       [ True,  True, False,  True,  True,  True,  True],
       [ True, False, False, False,  True,  True,  True]])

In [41]:
# Find which elements of the first array are greater than 7
a>7

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [ True, False, False,  True,  True,  True, False],
       [False, False, False, False, False, False, False]])

In [42]:
# Which parts of each array are equal? (try using '==')
a==b

array([[False,  True, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False,  True, False, False,  True],
       [ True, False, False, False,  True, False, False]])

In [43]:
# Sort one of the arrays you just created in ascending order
np.sort(a)

array([[2, 4, 5, 6, 6, 7, 7],
       [0, 0, 2, 2, 2, 4, 4],
       [2, 6, 6, 8, 9, 9, 9],
       [0, 3, 3, 4, 6, 6, 6]])

In [44]:
# Sort the indexes of one of the arrays you just created


In [45]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(a)

14

In [46]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(a)

8

In [47]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.sort(a,axis=1)

array([[2, 4, 5, 6, 6, 7, 7],
       [0, 0, 2, 2, 2, 4, 4],
       [2, 6, 6, 8, 9, 9, 9],
       [0, 3, 3, 4, 6, 6, 6]])

In [48]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.sort(b,axis=0)

array([[0, 0, 2, 5, 1, 0, 2],
       [3, 5, 3, 8, 3, 8, 2],
       [4, 5, 7, 8, 4, 8, 6],
       [6, 6, 8, 9, 6, 9, 8]])

In [49]:
# Create an array of normally distributed random numbers
np.random.randn(4,5)

array([[-0.90698723, -0.81735416, -0.48312268, -0.56982835, -2.09159967],
       [ 1.26374053, -0.01548334, -0.02737645,  0.81787351, -1.05460447],
       [-0.75832712,  0.45741565, -0.06437805,  0.34490234, -0.08008734],
       [-0.24138013,  1.43351549,  1.06579371, -2.49875914,  1.48032856]])

In [50]:
# Create an array with 10 evenly spaced numbers between 1 and 100
array=np.linspace(1,100,10)
array

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.